### ISSUE TITLE
Can you add nano to the box?

### ISSUE THREAD

**Issue by ChpcTraining** [HPC-Ecosystems/OpenHPC2-vcluster-downloadable#3]
Or should I ask them to install it as a step?

**Comment by brattex** [comment]
Vagrantfile can be configured to install apps after it launches the basic VM, so that IMHO is probably the easiest place to include stuff ... let me update the Vagrantfile ... I'll add a comment:

#installs

**Comment by brattex** [comment]
I am not sure that I have a formal answer for this - if you want nano installed, then it should either be baked into the main image, or custom added with Vagrantfile. 

I like the Vagrantfile option because it can be customised to add other things too (like it used to have) ...
